import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["cyrillic"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${interSans.className}  antialiased py-[53px] px-[16px] sm:px-[42px] container mx-auto `}
      >
        <Header/>
        <main className="mx-auto">
        {children}
        </main>
      </body>
    </html>
  );
}
